name: Trigger auto deployment for prod-connecteurerp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/prod-connecteurerp-AutoDeployTrigger-89aa17b2-26a9-4d39-9207-bfa79ad90583.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PRODCONNECTEURERP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: middlewareuat.azurecr.io
          registryUsername: ${{ secrets.PRODCONNECTEURERP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRODCONNECTEURERP_REGISTRY_PASSWORD }}
          containerAppName: prod-connecteurerp
          resourceGroup: middleware_rg
          imageToBuild: middlewareuat.azurecr.io/gs-spring-boot-docker:${{ github.sha }}
          
            

     

